- packages/storybook/package.json
- packages/storybook/src/preset.ts
- yarn.lock
Fixing this error
```
Error: ver] ✘ [ERROR] Cannot find module 'vite-plugin-node-polyfills/shims/buffer' from '.' [plugin node-stdlib-browser-alias]
[WebServer] 
[WebServer]     /home/runner/work/redmix/test-project/node_modules/resolve/lib/async.js:146:34:
[WebServer]       146 │                 var moduleError = new Error("Cannot find module '...
[WebServer]           ╵                                   ^
[WebServer] 
[WebServer]     at /home/runner/work/redmix/test-project/node_modules/resolve/lib/async.js:146:35
[WebServer]     at processDirs (/home/runner/work/redmix/test-project/node_modules/resolve/lib/async.js:299:39)
[WebServer]     at isdir (/home/runner/work/redmix/test-project/node_modules/resolve/lib/async.js:306:32)
[WebServer]     at …
```
> fix(storybook): Adding vite-plugin-node-polyfills to SB Vite config

- packages/cli/src/commands/deploy/__tests__/baremetal.test.js
Fixing this warning in CI
```
stderr | src/commands/deploy/__tests__/baremetal.test.js > deployTasks > throws an error if there is not enough available space on the server and freeSpaceRequired is not configured
Promise returned by `expect(actual).rejects.toThrowError(expected)` was not awaited. Vitest currently auto-awaits hanging assertions at the end of the test, but this will cause the test to fail in Vitest 3. Please remember to await the assertion.
at /home/runner/work/graphql/graphql/packages/cli/src/commands/deploy/__tests__/baremetal.test.js:705:40
```
> chore(cli): async await test that expects rejected promise

- packages/auth-providers/supertokens/setup/package.json
- packages/cli-packages/dataMigrate/package.json
- packages/cli/package.json
- packages/vite/package.json
- yarn.lock
From their changelog: 
* allow setting rdev on node (https://github.com/streamich/memfs/issues/1085) ([2717334](https://github.com/streamich/memfs/commit/2717334372ee92b1892ef12cdc341d43312455f2))
* support UInt8Array in place of Buffer (https://github.com/streamich/memfs/issues/1083) ([0d3662a](https://github.com/streamich/memfs/commit/0d3662a75f09fee7bfc6b73f26c34e0e2922bf6f))
> chore(deps): Bump memfs to 4.17.0

- .changesets/8.md
- docs/docs/tutorial/chapter1/first-page.md
- package.json
- packages/cli-helpers/package.json
- packages/cli/package.json
- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffold.test.js.snap
- packages/cli/src/commands/generate/scaffold/__tests__/__snapshots__/scaffoldNoNest.test.js.snap
- packages/codemods/package.json
- packages/create-redwood-rsc-app/package.json
- packages/create-redwood-rsc-app/src/installationDir.ts
- packages/create-redwood-rsc-app/yarn.lock
- packages/eslint-config/package.json
- packages/internal/package.json
- yarn.lock
See https://github.com/prettier/prettier/blob/main/CHANGELOG.md for changes.
This change affected us: https://prettier.io/blog/2025/02/09/3.5.0.html#css
Note: Prettier regards this as a minor change. But it did break our tests and
required code changes on our side. It might do the same for your project!
> chore(deps): Bump prettier to 3.5.3

- packages/realtime/package.json
- yarn.lock
> chore(deps): Bump ioredis to 5.6.0

- README.md
- tasks/all-contributors/.all-contributorsrc
Update list of Redwood contributors so I have just one list there. When it's complete I'll switch the config over to pull in Redmix contributors instead
> chore(docs): Update list of contributors

- packages/api/package.json
- packages/api/src/bins/redwood.ts
- packages/api/src/bins/rwfw.ts
- packages/core/src/bins/redwood.ts
- packages/core/src/bins/rw-api-server-watch.ts
- packages/core/src/bins/rw-dev-fe.ts
- packages/core/src/bins/rwfw.ts
- packages/web/src/bins/redwood.ts
- packages/web/src/bins/rwfw.ts
- packages/web/src/bins/storybook.ts
- tasks/test-project/tui-tasks.ts
Once we make `@redmix/cli` an ESM package we can no longer import it using `require`. By changing the bin files here to use `import` instead we make them compatible with with ESM as well as CJS
> chore(esm): Make redwood, rw, rwfw and storybook bins ESM compatible

- packages/cli/src/commands/deploy/baremetal.js
Silly breaking change. I'm pretty sure no one uses the export, but it is possible, so this is a breaking change 🙁
> chore(cli): Remove unused export from baremetal

- packages/cli/src/commands/destroy/cell/__tests__/cell.test.js
- packages/cli/src/commands/destroy/scaffold/__tests__/scaffold.test.js
- packages/cli/src/commands/destroy/scaffold/__tests__/scaffoldNoNest.test.js
- packages/cli/src/commands/generate/__tests__/createYargsForComponentGeneration.test.js
- packages/cli/src/commands/generate/__tests__/helpers.test.js
- packages/cli/src/commands/generate/cell/__tests__/cell.test.js
- packages/cli/src/commands/generate/cell/cell.js
- packages/cli/src/commands/generate/cell/cellHandler.js
- packages/cli/src/commands/generate/component/component.js
- packages/cli/src/commands/generate/dataMigration/dataMigration.js
- packages/cli/src/commands/generate/dbAuth/dbAuth.js
- packages/cli/src/commands/generate/directive/directive.js
- packages/cli/src/commands/generate/function/function.js
- packages/cli/src/commands/generate/helpers.js
- packages/cli/src/commands/generate/job/job.js
- packages/cli/src/commands/generate/layout/layout.js
- packages/cli/src/commands/generate/model/model.js
- packages/cli/src/commands/generate/ogImage/ogImage.js
- packages/cli/src/commands/generate/page/page.js
- packages/cli/src/commands/generate/scaffold/__tests__/editableColumns.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffold.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldCustomIdName.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/scaffoldNoNest.test.js
- packages/cli/src/commands/generate/scaffold/__tests__/shouldUseEmptyAsUndefined.test.js
- packages/cli/src/commands/generate/scaffold/scaffold.js
- packages/cli/src/commands/generate/script/script.js
- packages/cli/src/commands/generate/sdl/sdl.js
- packages/cli/src/commands/generate/service/service.js
- packages/cli/src/commands/generate/yargsCommandHelpers.js
- packages/cli/src/commands/generate/yargsHandlerHelpers.js
When moving to ESM we have to get rid of yargs' `.commandDir()` and instead `import` all files. When doing so we also have to split each command out into a separate handler() function that asynchronously imports things to not bloat the CLI and to not trigger unwanted side effects from imports (some imports run code just by being imported).
This PR preps for all of that by splitting up the cell generator as a proof of concept. It also splits a helper file into three separate files, two which are safe to sync import in the CLI and one which has to be async imported.
> chore(cli): commands/generate/cell: Separate async handler

- .changesets/31.md
- packages/babel-config/src/index.ts
We've been exporting a bunch of unnecessary stuff to keep backwards compatibility. This PR adds jsdocs to all exports marking those we don't use ourselves as deprecated. 
If you import from `@redmix/babel-config` you might get a deprecation warning in your editor.
Please let us know if you use any of these exports and we can discuss whether to keep it around or if there's a better solution.
> docs(babel-config): Add jsdocs to index exports

- .changesets/32.md
- .github/workflows/ci.yml
- __fixtures__/test-project/web/src/components/ClassWithPrivate/ClassWithPrivate.stories.tsx
- __fixtures__/test-project/web/src/components/ClassWithPrivate/ClassWithPrivate.test.tsx
- __fixtures__/test-project/web/src/components/ClassWithPrivate/ClassWithPrivate.tsx
- packages/babel-config/src/plugins/babel-plugin-redwood-routes-auto-loader.ts
- packages/babel-config/src/web.ts
- tasks/test-project/codemods/classWithPrivate.ts
- tasks/test-project/tui-tasks.ts
In Redwood PR # 10867 `https://github.com/redwoodjs/graphql/pull/ 10867`, which removed support for Webpack and moving us over to Vite only, these two lines were removed:
```ts
// Vite does not need these plugins
const commonPlugins = forVite ? [] : getCommonPlugins()
```
I'm assuming the thinking was "Since we're always building for Vite now, this will always just be `[]`, so we might as well get rid of all of this. The flaw in that reasoning is that there's another environment in which this code is invoked, and that's when testing with Jest. So when `withJest` is `true` `getCommonPlugins()` still needs to be called and the resulting list of plugins need to be included.
This PR adds the list of common plugins back into the config when used by/for Jest.
Here's the CI output without the …
> fix(app tests): Fix v8 regression with classes

- packages/cli/src/commands/generate/cell/cell.js
- packages/cli/src/commands/generate/component/component.js
- packages/cli/src/commands/generate/dbAuth/dbAuth.js
- packages/cli/src/commands/generate/directive/directive.js
- packages/cli/src/commands/generate/function/function.js
- packages/cli/src/commands/generate/job/job.js
- packages/cli/src/commands/generate/layout/layout.js
- packages/cli/src/commands/generate/model/model.js
- packages/cli/src/commands/generate/ogImage/ogImage.js
- packages/cli/src/commands/generate/yargsCommandHelpers.js
Provide a convenience helper for creating command handlers that asynchronously imports the handler function when invoked.
> refactor(cli): createHandler() command helper

- .changesets/42.md
- __fixtures__/test-project/web/config/tailwind.config.js
- packages/cli/src/commands/setup/ui/libraries/tailwindcss.js
Use an absolute path so Tailwind also works for Storybook components
> fix(cli/setup): Fix Tailwind setup to work with Storybook

- __fixtures__/test-project/redwood.toml
- packages/create-redmix-app/templates/js/redwood.toml
- packages/create-redmix-app/templates/ts/redwood.toml
Not all projects will use dbAuth, so shouldn't mention it in the redwood.toml file every project gets.
This change only updates our templates. Does not affect existing projects. And no need for any existing projects to make any changes.
> fix(crxa): Remove comment referencing dbAuth

- __fixtures__/test-project/package.json
- __fixtures__/test-project/web/package.json
- tasks/test-project/rebuild-test-project-fixture.ts
- tasks/test-project/tui-tasks.ts
Make it possible to test bins on the api side (like the `@redmix/api` bins) in the test project. 
Simplify (and make more realistic) the Tailwind setup step
> chore(test-project): Fix rebuilding

- packages/api/build.mts
- packages/api/src/index.ts
- packages/graphql-server/src/rootSchema.ts
Testing a new approach that tries to stick closer to the original by just using `require`, but doing so in a way that works for both CJS and ESM.
This reverts a bunch of the changes made in #45 plus all of https://github.com/redmix-run/redmix/commit/3646c569f88779afd28318ade78545b64081a196
> chore(api): Only async version consts

- docs/docs/graphql.md
- packages/graphql-server/src/__tests__/createGraphQLYoga.test.ts
- packages/graphql-server/src/createGraphQLYoga.ts
`createGraphQLYoga` should not crash if optional parameters are not provided
> fix(graphql-server): Don't require healthCheckId

- packages/api-server/src/createServer.ts
- packages/api-server/src/plugins/graphql.ts
- packages/babel-config/src/plugins/babel-plugin-redwood-graphql-options-extract.ts
https://github.com/redwoodjs/graphql/pull/9845 introduced a babel plugin to extract the options that are passed to `createGraphQLHandler` into an internal variable `__rw_graphqlOptions`.
If no options to extract could be found the variable would not be created. 
In `@redmix/graphql-server` this would lead to passing `undefined` to `createGraphQLYoga()`, which in turn would cause an exception to be thrown that we'd catch and log.
With this PR we assume the user is doing their own thing that they want full control over. So instead of trying to create a Redmix gql handler and failing, we instead entirely just skip our own handling if no `__rw_graphqlOptions` variable is exported
> fix(api-server): Allow fully custom graphql function

- packages/cli/src/commands/execHandler.js
Pass the `--silent` option onwards to `generatePrismaClient` so that the user's will to silence the output is honored for that step as well
> fix(exec): Honor --silent for prisma client generation step

- packages/cli/src/lib/generatePrismaClient.js
- tasks/e2e-background-jobs/run.mts
Use `await import` when getting the Prisma client instead of `require` to make the code ready for ESM.
I'm marking this as a feature because I'm a little worried about how this works together with Babel.
Also of note is I had to add code to clear our require cache. Which is a good sign as far as Babel support for this code goes (because Babel works with `require()`). But also makes it more difficult to actually make this code ESM ready, since ESM doesn't use require (and so, also doesn't use the require cache)
> feat(cli): await import Prisma client to support ESM

- packages/babel-config/package.json
- packages/babel-config/src/common.ts
- yarn.lock
Prefer DefinitelyTyped types to our own. The DT types also provide some extra JSDoc comments that are nice to have.
With this PR I deprecate our own `BabelRegisterOptions` type that's exported from `@redmix/cli`. No one should be importing from here, but potentially they could be doing so. So I've marked it deprecated rather than removing it for now. If someone *is* using our type, they should just import from the same DT package as we are.
> chore(babel-config): Use types from @babel/register

- .github/renovate.json
- packages/cli/package.json
- packages/cli/src/lib/updateCheck.js
- yarn.lock
https://github.com/sindresorhus/latest-version/releases
Breaking changes since our previous version is mainly that it has changed to be ESM only, plus now requires a more modern version of Node (v18+). But we're on v20, so that's not a problem for us.
> chore(deps): Upgrade latest-version to v9.0.0 (which is ESM only)

- .github/workflows/ci.yml
https://github.com/cypress-io/github-action/releases/tag/v6.9.0
> chore(ci): Upgrade cypress-io action to v6.9.0

- .changesets/67.md
- packages/auth-providers/dbAuth/api/package.json
- packages/auth-providers/dbAuth/api/src/DbAuthHandler.ts
- packages/auth-providers/dbAuth/setup/package.json
- packages/auth-providers/dbAuth/setup/src/webAuthn.setupData.ts
- packages/auth-providers/dbAuth/web/package.json
- packages/cli/src/commands/generate/dbAuth/__tests__/dbAuth.mockListr.test.js
- yarn.lock
Update SimpleWebAuthn from v7 to v9 to stop using deprecated package `@simplewebauthn/typescript-types` (it's now `@simplewebauthn/types` instead)
Users will have to upgrade to:
- `@simplewebauthn/server@9.0.3`
- `@simplewebauthn/browser@9.0.1`
- `@simplewebauthn/types@9.0.1`
And remove dependency
- `@simplewebauthn/typescript-types`
> chore(deps): Upgrade SimpleWebAuthn to v9

- packages/api-server/src/bin.ts
- packages/cli/src/commands/serveBothHandler.js
Found a couple of imports that still needed a `.js` extension now that the cli is ESM. Only noticed it after another PR triggered our Streaming and RSC CI workflows
> fix(cli): Import from api-server using .js

- packages/api/src/index.ts
From the comment in the code:
```
// The argument to `createRequire` should be a file and node will strip
// the last segment (the file name) to get to a base path. By appending a
// fake "foo" file we get the base path we want
// If I knew this was only going to be run as an ESM I'd use
// `import.meta.url`, but for dual bundling I can't do that (without a
// bunch of warnings at build time at least)
```
> fix(api): Fix creation of customRequire

- packages/api/src/index.ts
Doing this:
`typeof require === 'function' && !require.toString().includes('@rollup') ? require`
Rollup would transform that to:
`typeof commonjsRequire === "function" && !require.toString().includes("@rollup") ? commonjsRequire`
And running that you'd get an error saying "ReferenceError: require is not defined in ES module scope, you can use import instead". By doing `(0, require)`, Rollup realizes that it's the global `require` we're working with, so it gets the same treatment as the other `require`s.
> fix(api): Work around Rollup transforms messing with the code

- __fixtures__/rsc-caching/api/package.json
- __fixtures__/rsc-caching/package.json
- __fixtures__/rsc-caching/web/package.json
- __fixtures__/test-project-rsa/api/package.json
- __fixtures__/test-project-rsa/package.json
- __fixtures__/test-project-rsa/web/package.json
- __fixtures__/test-project-rsc-kitchen-sink/api/package.json
- __fixtures__/test-project-rsc-kitchen-sink/package.json
- __fixtures__/test-project-rsc-kitchen-sink/web/package.json
The code was previously using Redmix package names, but Redwood package versions. Now it's using Redmix package versions that actually exists (i.e. published to npm)
> chore(test-project): RSC: Use published `@redmix` package versions

- packages/context/package.json
Fixing this error I got when trying to switch a Redmix project over to ESM:
```
api |
api | Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/store.js' is not defined by "exports" in /Users/tobbe/tmp/rx-esm-1/node_modules/@redmix/context/package.json imported from /Users/tobbe/tmp/rx-esm-1/api/dist/functions/graphql.js
api |     at exportsNotFound (node:internal/modules/esm/resolve:322:10)
api |     at packageExportsResolve (node:internal/modules/esm/resolve:670:9)
api |     at packageResolve (node:internal/modules/esm/resolve:856:14)
api |     at moduleResolve (node:internal/modules/esm/resolve:946:18)
api |     at defaultResolve (node:internal/modules/esm/resolve:1188:11)
api |     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:642:12)
api |     at …
```
> fix(context): Add .js to export for ESM compatibility

- package.json
- packages/auth-providers/dbAuth/setup/package.json
- packages/auth-providers/dbAuth/web/package.json
- packages/auth/package.json
- packages/babel-config/dist.test.ts
- packages/babel-config/package.json
- packages/babel-config/src/__tests__/api.test.ts
- packages/cli/package.json
- packages/codemods/package.json
- packages/graphql-server/package.json
- packages/internal/package.json
- packages/router/package.json
- packages/structure/package.json
- packages/vite/package.json
- packages/web/package.json
- yarn.lock
- Changes [v3.41.0...v3.42.0](https://github.com/zloirock/core-js/compare/v3.41.0...v3.42.0) (142 commits)
- [`Map` upsert proposal](https://github.com/tc39/proposal-upsert):
- Moved to stage 2.7, [April 2025 TC39 meeting](https://x.com/robpalmer2/status/1911882240109261148)
- Validation order of `WeakMap.prototype.getOrInsertComputed` updated following [tc39/proposal-upsert#79](https://github.com/tc39/proposal-upsert/pull/79)
- Built-ins:
- `Map.prototype.getOrInsert`
- `Map.prototype.getOrInsertComputed`
- `WeakMap.prototype.getOrInsert`
- `WeakMap.prototype.getOrInsertComputed`
- Don't call well-known `Symbol` methods for `RegExp` on primitive values following [tc39/ecma262#3009](https://github.com/tc39/ecma262/pull/3009):
- For avoid performance regression, temporarily, only in own …
> chore(deps): Bump core-js to 3.42.0

- packages/api-server/src/__tests__/createServer.test.ts
- packages/api-server/src/apiCLIConfigHandler.ts
- packages/api-server/src/createServerHelpers.ts
The `rw-server` bin was documented to have `--port` and `--host` command line options, but they were never actually used. `-p` would work, but not `--port`. You could configure them both before using env vars, and you still can, but now also the long version of the command line arguments work.
> fix(api-server): Use --port and --host options

- packages/api-server/src/__tests__/createServer.test.ts
I was getting this error about what address the server was listening to
```
- Expected
+ Received
Object {
"level": 30,
-   "msg": "Server listening at http://[::1]:8910",
+   "msg": "Server listening at http://127.0.0.1:8910",
}
❯ src/__tests__/createServer.test.ts:178:27
```
This PR fixes that by not caring about the order of the log lines
> chore(api-server): More forgiving unit tests

- yarn.lock
Update tar-fs to fix https://github.com/cedarjs/cedar/security/dependabot/70
> chore(deps): Upgrade tar-fs to 2.1.3

- yarn.lock
Fix https://github.com/cedarjs/cedar/security/dependabot/67
> chore(deps): Upgrade elliptic to 6.6.1

- docs/yarn.lock
Attempting to fix https://github.com/cedarjs/cedar/security/dependabot/9 potentially also https://github.com/cedarjs/cedar/security/dependabot/7
> chore(deps): Upgrade path-to-regexp to 0.1.12 and to 1.9.0

- packages/internal/src/generate/templates/all-currentUser.d.ts.template
* Link to cedarjs.com instead of redwoodjs.com
* Use a regular space instead of unicode character U+A0
This is what it looked like before
> fix(jsdoc): currentUser: Update link and remove unusual whitespace

- .prettierignore
- lefthook.yml
- package.json
- yarn.lock
Add git hooks to run a few quick checks on commit and push
Note: I'm running prettier with `--log-level=silent` to work around this issue: https://github.com/evilmartians/lefthook/issues/1047
If I didn't have to do that I'd rather use `- run: yarn format:check` to align the lefthook check with our package.json script to make sure they're always in sync.
> chore(git): Add lefthook

- README.md
Update the instructions for migrating from Redwood to CedarJS to make them more clear and detailed.
> docs(README): Update the migration notes

- .changesets/151.md
- packages/api/src/cache/__tests__/cache.test.ts
- packages/api/src/cache/__tests__/cacheFindMany.test.ts
- packages/api/src/cache/__tests__/deleteCacheKey.test.ts
- packages/api/src/cache/__tests__/disconnect.test.ts
- packages/api/src/cache/clients/BaseClient.ts
- packages/api/src/cache/clients/InMemoryClient.ts
- packages/api/src/cache/clients/MemcachedClient.ts
- packages/api/src/cache/clients/RedisClient.ts
- packages/api/src/cache/index.ts
Fixes #150
Not exactly sure why but it does the trick.
> fix(api/cache): use named exports instead of default exports

- .github/actions/set-up-job/action.yml
- .github/workflows/publish-canary.yml
- .github/workflows/publish-release-candidate.yml
- .gitpod.yml
- CONTRIBUTING.md
- docs/docs/docker.md
- docs/docs/how-to/test-in-github-actions.md
- docs/docs/how-to/using-nvm.md
- docs/docs/how-to/using-yarn.md
- docs/docs/tutorial/chapter1/prerequisites.md
- packages/cli/src/commands/setup/deploy/templates/render.js
- packages/cli/src/commands/setup/docker/templates/Dockerfile
- packages/create-cedar-rsc-app/src/prerequisites.ts
More context here https://github.com/redwoodjs/graphql/pull/12028, but basically corepack will soonish have to be installed from npm as it will no longer be shipped with Node. This PR makes sure we're prepared for that. And it also aligns our docs with the latest yarn docs.
Thanks to @trivikr for getting the PR started over in the Redwood repo 🙏 
This PR mostly updates docs and CI related files. 
But it does also touch our Render and Docker setup scripts. 
⚠️ If you're deploying to Render, or using Docker, you will probably want to manually make these changes to your own app
There's some good discussion related to corepack on GitHub runners here: https://github.com/actions/setup-node/issues/1222
> fix(corepack): Switch to installing corepack globally from npm

- packages/auth-providers/supertokens/setup/src/__tests__/setupHandler.test.ts
- packages/auth-providers/supertokens/setup/src/setupHandler.ts
I was upgrading to Vitest 3.x and noticed one of our snapshot tests started failing. Looking into it I realized we weren't handling whitespace properly when setting up Supertokens auth. This PR fixes that.
I'm guessing this is the Vitest change that caused the diff in snapshots: https://github.com/vitest-dev/vitest/pull/7400
It doesn't say in the PR description, but the [release notes for Vitest 3.1.0](https://github.com/vitest-dev/vitest/releases/tag/v3.1.0), where it was first included, says
> This change can cause small amount of very old snapshots to be updated, but there will be no functional change to how they work.
> fix(supertokens): Fix whitespace handling in setup script

- packages/cli-helpers/src/lib/__tests__/version.test.ts
- packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.ts
I was seeing this error on CI https://cloud.nx.app/runs/eLSbQ5d7FY/task/%40cedarjs%2Fvite%3Atest
```
Promise returned by `expect(actual).rejects.toThrowErrorMatchingInlineSnapshot(expected)` was not awaited. Vitest currently auto-awaits hanging assertions at the end of the test, but this will cause the test to fail in Vitest 3. Please remember to await the assertion.
at /home/runner/work/cedar/cedar/packages/vite/src/plugins/__tests__/vite-plugin-rsc-route-auto-loader.test.ts:332:21
```
This PR properly adds `await`
> chore(tests): Await rejects.toThrowErrorMatchingInlineSnapshot

- packages/storybook/package.json
- yarn.lock
See https://github.com/joshwooding/vite-plugin-react-docgen-typescript/releases for changes
> chore(deps): Bump `@joshwooding/vite-plugin-react-docgen-typescript` to v0.6.1

- packages/storybook/src/index.ts
- packages/storybook/src/mocks/MockProviders.tsx
- packages/storybook/src/mocks/StorybookProvider.tsx
- packages/storybook/src/plugins/react-docgen.ts
- packages/storybook/src/preset.ts
- packages/storybook/src/preview.tsx
- packages/storybook/src/types.ts
- packages/storybook/tsconfig.json
Using modern tsconfig settings:
```json
"module": "nodenext",
"moduleResolution": "nodenext",
```
Allowed me to remove this workaround I had in place:
```json
"paths": {
"@cedarjs/testing/auth": ["../testing/dist/web/mockAuth.d.ts"],
"@cedarjs/testing/web": ["../testing/dist/web/index.d.ts"]
}
```
> chore(storybook): tsconfig module and moduleResolution nodenext

- packages/cli/src/commands/setup/middleware/ogImage/__codemod_tests__/vitePlugin.ts
- packages/cli/src/testUtils/matchTransformSnapshot.ts
Trying to work around this error in our CI
Discussion here: https://github.com/vitest-dev/vitest/discussions/6511
Original issue on vitest: https://github.com/vitest-dev/vitest/issues/6479
> chore(tests): Flush promises before running test

- packages/vite/src/build/__tests__/buildWeb.test.ts
I'm seeing this error on CI https://github.com/cedarjs/cedar/actions/runs/16095689619/job/45418357644?pr=172
Adding some performance measurements to help me understand exactly what's taking so long
> chore(vite): Track performance in buildWeb test

- tasks/e2e-background-jobs/run.mts
Breaks the test up into smaller functions so that it's easier to get an overview of what it's doing, and so that I can more easily add test for cron jobs as part of https://github.com/cedarjs/cedar/pull/180
> chore(e2e): Break job e2e script up into smaller functions

- .changesets/189.md
- packages/api-server/src/__tests__/createServer.test.ts
- packages/api-server/src/__tests__/lambdaLoader.test.ts
- packages/api-server/src/createServer.ts
- packages/api-server/src/createServerHelpers.ts
- packages/api-server/src/plugins/api.ts
- packages/api-server/src/plugins/lambdaLoader.ts
- packages/internal/src/files.ts
For function discovery in createServer and related modules.
Allows overriding the glob used to discover functions, which is required when a different bundler is used, or the directory structure is not the default `dist/functions/`
Defaults to: `'dist/functions/**/*.{ts,js}'`
All credit for this one goes to @richard-stafflink who created the original PR over at https://github.com/redwoodjs/graphql/pull/12063
> feat(api-server): lambdaLoader: add discoverFunctionsGlob option

- .changesets/190.md
- packages/api-server/src/plugins/lambdaLoader.ts
For ESModule and CommonJS compatibility.
When using a bundler like Rollup, the handler function is exported as `default`.
This change defaults to a named `handler` export, just like before. But if an export like that can't be found it'll now also look for a `default` export with a `handler` property on it.
All credit for this one goes to @richard-stafflink who created the original PR over at https://github.com/redwoodjs/graphql/pull/12064
> fix(api-server): lambdaLoader: improve handler import logic

- packages/cli/src/commands/upgrade.js
CedarJS doesn't have any forums, so it's better to just direct people to our Discord
> feat(cli): upgrade command: Link to Discord instead of forums

- packages/api/package.json
- packages/api/src/bins/cedarjs.ts
- packages/cli/package.json
- packages/core/src/bins/cedarjs.ts
- packages/web/package.json
- packages/web/src/bins/cedarjs.ts
- yarn.lock
Added `cedarjs` and `cj` bins in addition to the existing `redwood` and `rw` bins. So you can do things like `yarn cj info` or `yarn cj g page about`
> feat(cli): cedarjs and cj bins

- .github/actions/require-release-label-or-cc-message/action.yml
- .github/actions/require-release-label-or-cc-message/requireReleaseLabelOrCcMessage.mjs
- .github/workflows/require-release-label.yml
If the PR title starts with `chore(scope):`, `feat(scope):`, `fix(scope):` or `docs(scope):` a release label is not required.
> chore(ci): Accept conventional commits style title in addition to labels

- packages/core/package.json
- yarn.lock
This should have been part of https://github.com/cedarjs/cedar/pull/195
`cedarjs` and `cj` needs to be part of the core package, because that's the package that the root package.json in a CedarJS app has installed
> fix(core): Add missing bin fields to core/package.json

- packages/api/src/webhooks/index.ts
I was getting errors like these:
```
FAIL   api  src/directives/requireAuth/requireAuth.test.ts [ api/src/directives/requireAuth/requireAuth.test.ts ]
SyntaxError: The requested module '../auth/verifiers/index.js' does not provide an export named 'SupportedVerifierTypes'
❯ src/directives/requireAuth/requireAuth.test.ts:1:1
1| import { mockRedwoodDirective, getDirectiveName } from '@cedarjs/testing/api'
| ^
2|
3| import requireAuth from './requireAuth.js'
```
This PR should fix that by making sure `SupportedVerifyerTypes` is properly imported from the correct location
> fix(api): Fix SupportedVerifierTypes import

- packages/api/src/webhooks/index.ts
- packages/api/src/webhooks/webhooks.test.ts
- packages/api/src/webhooks/webhooks.type.test.ts
This is a continuation of #207 
While that PR correctly fixed the imports, the exports were still wrong
This PR changes the exports from using their own import paths to just re-exporting what was already imported, making sure we don't forget to update both paths in the future (because now there is only one path to update)
Also added type tests to make sure the exports are what we expect.
> fix(api): Fix webhook exports

- packages/mailer/handlers/resend/package.json
- packages/mailer/handlers/resend/src/index.ts
- yarn.lock
Here are the breaking changes for v4: https://github.com/resend/resend-node/releases/tag/v4.0.0
Basically `reply_to` was changed to `replyTo`, and `attachments[].content_type` changed to `attachments[].contentType`. If you were setting any of those manually you'll have to update your code (even before this version bump we had `replyTo` in our interface and changed that to `reply_to` for Resend for you. So should hopefully not have to change anything there. For `content_type`, that was not something we exposed. So unless you were using Resend directly that change also should not affect you.
Full list of changes for all versions: https://github.com/resend/resend-node/releases
> chore(deps): Bump Resend from v3.5.0 to v4.6.0

- yarn.lock
This bumps the version of undici across various dependencies. The most important one being the bump to v5.29.0 to fix a few security issues, for example these two
> chore(deps): Bump transient dependency undici

- packages/create-cedar-rsc-app/package.json
- packages/create-cedar-rsc-app/yarn.lock
TS types are now part of the main eslint package
Should fix this renovate warning
> chore(deps): Remove deprecated package `@types/eslint__js`. It's not needed anymore

- .github/renovate.json
- packages/auth-providers/dbAuth/setup/package.json
- yarn.lock
This should have been part of #138 but was somehow missed.
Plus, enable renovate for termi-link, so I get notified of updates
> chore(deps): Fix dependency on termi-link

- yarn.lock
Fixes this security alert
axios is a transitive dependency because of nx
> chore(deps): Bump Axios to v1.8.2

- .github/workflows/ci.yml
Renovate is giving me this error message
> Could not determine new digest for update (github-tags package cypress-io/github-action)
So I'm updating it manually now. Maybe with a new commit sha it starts working again 🤷
> chore(deps): cypress-io/github-action v6.10.1

- .github/actions/detect-changes/cases/ssr.mjs
- .github/actions/detect-changes/detectChanges.mjs
The SSR test project uses dbAuth, so we should make sure the SSR tests still pass after making changes to dbAuth 
(This would have prevented the regression introduced in #245 and later fixed in #257)
> chore(ci): Include dbAuth in SSR change detection

- packages/auth-providers/dbAuth/web/.babelrc.js
- packages/auth-providers/dbAuth/web/build.ts
- packages/auth-providers/dbAuth/web/package.json
- packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.middleware.test.ts
- packages/auth-providers/dbAuth/web/src/__tests__/dbAuth.test.ts
- packages/auth-providers/dbAuth/web/src/__tests__/webAuthn.test.ts
- packages/auth-providers/dbAuth/web/src/dbAuth.ts
- packages/auth-providers/dbAuth/web/src/index.ts
- packages/auth-providers/dbAuth/web/src/webAuthn.ts
- packages/auth-providers/dbAuth/web/tsconfig.build.json
- packages/auth-providers/dbAuth/web/tsconfig.cjs.json
- packages/auth-providers/dbAuth/web/tsconfig.json
- packages/auth-providers/dbAuth/web/webAuthn/index.js
- packages/auth-providers/dbAuth/web/webAuthn/package.json
- packages/vite/src/devFeServer.ts
- packages/vite/src/rsc/rscBuildForSsr.ts
- packages/vite/src/streaming/buildForStreamingServer.ts
- yarn.lock
Need this to get full ESM support in Cedar apps with `"type": "module"`
I tried this in #245, but had a regression for SSR and RSC. This PR includes updated vite config to fix that regression
> feat(dbAuth): Dual mode ESM+CJS dbAuth web package

- packages/cli/src/commands/setup/graphql/features/fragments/__codemod_tests__/appGqlConfigTransform.test.ts
- packages/cli/src/commands/setup/graphql/features/fragments/__codemod_tests__/appImportTransform.test.ts
- packages/cli/src/commands/setup/graphql/features/trustedDocuments/__codemod_tests__/grapqlTransform.test.ts
- packages/cli/src/commands/setup/middleware/ogImage/__codemod_tests__/middleware.ts
- packages/cli/src/commands/setup/middleware/ogImage/__codemod_tests__/vitePlugin.ts
- packages/cli/src/commands/setup/uploads/__codemod_tests__/dbCodemod.test.ts
This is a re-implementation of #254, so I'm going to copy the description from there:
The cli package codemod tests are flaky on Windows CI, blocking all the dependabot PRs that could otherwise be automatically merged.
I hate doing this, but right now I don't know how to make them non-flaky. 
See this discussion thread for a bit more context https://github.com/vitest-dev/vitest/discussions/6511
And here's a previous attempt at fixing this issue: https://github.com/cedarjs/cedar/pull/235
> chore(ci): use skipIf to skip codemod tests on Windows CI

- packages/graphql-server/src/plugins/useRedwoodTrustedDocuments.ts
Studio is broken for the mail feature if trusted documents store is enabled. See https://github.com/redwoodjs/studio/issues/75
This fixes the issue:
This was the first initialization of studio with a test project, as you can see the second example is not showing and there's a copy remnant there. With trusted documents it's not synchronizing effectively.
This shows that studio synchronizes effectively after the changes in this PR.
EDIT by Tobbe:
I wanted to surface this really informative code comment:
```js
/**
* When using Studio, we want to allow the `resyncMailRenderers` and
* `resyncMailTemplate` mutations to be executed without a persisted operation.
* This is only allowed in local development, ensure you have
* NODE_ENV=development set.
*
* This is because the `resyncMailRenderers` …
```
> feat(gql): Trusted Documents support for CedarJS Mailer

- packages/prerender/src/build-and-import/buildAndImport.ts
- packages/prerender/src/build-and-import/utils.ts
For Cedar projects we can always just read the info we need from package.json files. No need to have fancy guessing in place. So this is a quick refactor to clean up the code a bit
> chore(prerender): Don't guess project format - read from package.json

- tasks/smoke-tests/auth/tests/authChecks.spec.ts
- tasks/smoke-tests/auth/tests/rbacChecks.spec.ts
Fixing errors like these
> Unexpected `await` of a non-Promise (non-"Thenable") value. (eslint @typescript-eslint/await-thenable)
> chore(ci): Remove unneeded awaits in specs

- packages/prerender/src/build-and-import/buildAndImport.ts
- packages/prerender/src/build-and-import/rollupPlugins/__tests__/rollup-plugin-cedarjs-routes-auto-loader.test.ts
- packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-routes-auto-loader.ts
- packages/prerender/src/build-and-import/rollupPlugins/utils.ts
Fix a bug where you couldn't lazy load a page called "FooPage" when prerendering
Also added a `dedent` utility function to clean up both the actual implementation and the tests
Plus added an extra test for nested pages
> fix(prerender): Fix FooPage bug

- packages/prerender/src/build-and-import/buildAndImport.ts
- packages/prerender/src/build-and-import/rollupPlugins/__tests__/rollup-plugin-cedarjs-routes-auto-loader.test.ts
- packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-routes-auto-loader.ts
This code only ever runs in the context of prerendering, so no need to ever support anything else than that
> chore(prerender): Remove forPrerender arg as it was always true

- packages/prerender/src/build-and-import/buildAndImport.ts
- packages/prerender/src/runPrerender.tsx
Use the built components to make sure we don't end up with multiple versions of modules in memory. Especially critical for React that compares objects with `===` to check if they're the same
> fix(prerender): Use built LocationProvider

- packages/prerender/src/build-and-import/rollupPlugins/rollup-plugin-cedarjs-prerender-media-imports.ts
- packages/prerender/src/graphql/graphql.ts
Using `readFile` instead of `require()` makes the code compatible with ESM
> chore(prerender): Use readFile instead of require for json file

- packages/graphql-server/src/plugins/useRedwoodGlobalContextSetter.ts
Our context implementation has moved to `@cedarjs/context` (from graphql-server where it used to live). This happened a while ago, but this jsdoc comment was still pointing towards the old location
> fix(graphql-server): Point towards correct context import

- packages/api/build.mts
- packages/api/src/index.ts
I was using `process.env.RWJS_CWD` when creating a new `require()` function, but `RWJS_CWD` isn't always an absolute path, so that doesn't work. `import.meta.url` does work, but only ESM. And the code, as it's written, will only execute that branch on ESM, but esbuild doesn't know that, so we'll get a warning during build that I now have to silence (https://esbuild.github.io/api/#log-override)
> fix(api): Fix createRequire for ESM

- packages/api-server/vitest.config.mts
The test started being flaky on Windows, so I'm increasing the timeout from 10s to 30s for Windows
Example of failing run: https://github.com/cedarjs/cedar/actions/runs/16549745453/job/46802880280?pr=300
> chore(api-server): Increase test timeout on Windows

- packages/context/src/context.ts
`createContextProxy` is only used in the same file a few lines down. It shouldn't be exported.
> fix(context): Don't export function that's only used internally

- .github/workflows/ci.yml
- package.json
- tasks/e2e/cypress.config.js
- tasks/e2e/cypress/e2e/01-tutorial/sharedTests.js
- tasks/e2e/cypress/e2e/01-tutorial/tutorial.cy.js
- tasks/run-e2e.cjs
I had to run Cypress locally to debug an issue with https://github.com/cedarjs/cedar/pull/316
And in doing so I wanted to fix a few code warnings, code style things, and move more of the code from mentioning RW to Cedar instead.
> chore(ci): Cypress: Fix eslint, RW->Cedar and remove commented code

- packages/codemods/src/codemods/v7.x.x/updateGraphQLConfig/updateGraphqlConfig.ts
Now that we have stable releases of CedarJS to link to, we should do that (just as the TODO told us!)
> fix(codemods): Link to git tag on GitHub for graphql config download

- tasks/test-project/tasks.js
- tasks/test-project/tui-tasks.ts
Indenting code snippets inline with the code around them makes it quicker and easier to visually scan where methods and other control blocks start and end
> chore(test-project): Update indentation for easier visual scanning

- packages/web/src/apollo/index.tsx
This was originally done as part of #80, but it's a change I want no matter what happens to that PR, so I'm merging it on its own. This allows `@apollo/client` imports work in both CJS and ESM contexts.
As noted in the issue I've linked in the comments, https://github.com/apollographql/apollo-feature-requests/issues/287, this will be resolved once they release v4 and we upgrade to that version
> chore(esm): Make `@apollo/client` imports more ESM friendly

- packages/cli/src/commands/setup/ui/libraries/tailwindcssHandler.js
The code comment explains this pretty well
```ts
// `tailwindcss init` will generate ESM syntax when it detects
// `"type": "module"` in package.json, even though the config
// file is .cjs. So we change it back to CJS syntax after it's
// been generated.
```
This is part of the ESM prep work started in #349
> feat(esm): Support running Tailwind setup in ESM projects

- packages/create-cedar-app/package.json
- yarn.lock
Even though this is a major version bump of a dependency from v6 to v7, it's only used as a devDep and has no impact on user's apps. So this is just a chore commit
(klaw-sync had to do a major version bump because they changed how they handle symlinks, but that doesn't affect us)
> chore(deps): Upgrade klaw-sync to v7.0.0

- packages/storybook/src/plugins/mock-router.ts
- packages/testing/build.mts
- packages/testing/package.json
- packages/testing/src/api/mockContext.ts
- packages/testing/src/api/vitest/CedarApiVitestEnv.ts
- packages/testing/src/api/vitest/index.ts
- packages/testing/src/api/vitest/vite-plugin-auto-import.ts
- packages/testing/src/api/vitest/vite-plugin-cedar-vitest-api-config.ts
- packages/testing/src/api/vitest/vite-plugin-track-db-imports.ts
- packages/testing/src/api/vitest/vitest-api.setup.ts
- packages/testing/src/web/MockProviders.tsx
- packages/testing/src/web/MockRouter.tsx
- packages/testing/src/web/globRoutesImporter.ts
- packages/testing/src/web/vitest/index.ts
- packages/testing/src/web/vitest/vite-plugin-auto-import.ts
- packages/testing/src/web/vitest/vite-plugin-cedarjs-router-import-transform.ts
- packages/testing/src/web/vitest/vite-plugin-create-auth-import-transform.ts
- packages/testing/tsconfig.cjs.json
- packages/vite/src/index.ts
- packages/vite/src/lib/getMergedConfig.ts
- packages/vite/tsconfig.build.json
- packages/vite/tsconfig.json
Yet another PR (5/n) for ESM support. See #349 for where this recent chain of PRs started
> feat(esm): Add vitest plugins and config to packages/testing

- packages/vite/package.json
- packages/vite/src/api/vite-plugin-cedar-vitest-api-preset.ts
- yarn.lock
Bringing over the last `packages/vite` changes from #80 to the `main` branch
> feat(esm): packages/vite api side vitest support

- packages/testing/package.json
- yarn.lock
`unplugin-auto-import` is used in vite plugins that we added in #355 
PR (7/n) for adding ESM support. See #349 for PR 1/n in the series
> feat(esm): Add missing dependency to `packages/testing`

- packages/storybook/src/plugins/mock-router.ts
- packages/testing/build.mts
- packages/testing/package.json
- packages/testing/src/api/mockContext.ts
- packages/testing/src/api/vitest/CedarApiVitestEnv.ts
- packages/testing/src/api/vitest/index.ts
- packages/testing/src/api/vitest/vite-plugin-auto-import.ts
- packages/testing/src/api/vitest/vite-plugin-cedar-vitest-api-config.ts
- packages/testing/src/api/vitest/vite-plugin-track-db-imports.ts
- packages/testing/src/api/vitest/vitest-api.setup.ts
- packages/testing/src/web/MockProviders.tsx
- packages/testing/src/web/MockRouter.tsx
- packages/testing/src/web/globRoutesImporter.ts
- packages/testing/src/web/vitest/index.ts
- packages/testing/src/web/vitest/vite-plugin-auto-import.ts
- packages/testing/src/web/vitest/vite-plugin-cedarjs-router-import-transform.ts
- packages/testing/src/web/vitest/vite-plugin-create-auth-import-transform.ts
- packages/testing/tsconfig.cjs.json
- packages/vite/src/index.ts
- packages/vite/src/lib/getMergedConfig.ts
- packages/vite/tsconfig.build.json
- packages/vite/tsconfig.json
> feat(esm): Add vitest plugins and config to packages/testing (take 2)

- packages/vite/package.json
- packages/vite/src/api/vite-plugin-cedar-vitest-api-preset.ts
- yarn.lock
> feat(esm): packages/vite api side vitest support (take 2)

- packages/testing/package.json
- yarn.lock
`unplugin-auto-import` is used in vite plugins that we added in https://github.com/cedarjs/cedar/pull/355 and then again in #362 
This PR is re-applying #360
> feat(esm): Add missing dependency to `packages/testing` (take 2)

- packages/create-cedar-app/src/create-cedar-app.js
- packages/create-cedar-app/tests/e2e.test.ts
With this PR I add support for a hidden `--esm` flag you can pass to `yarn create cedar-app` to generate an app based on our ESM template
Until #80 is merged, the ESM app will not have full functionality. So for now, generation works, but you can't run it
PR 15/n in the #349 series
> feat(esm): Create ESM Cedar App using hidden --esm flag

- packages/prerender/src/build-and-import/buildAndImport.ts
Use correct `gql` import depending on ESM vs CJS projects
16/n in #349 series
> feat(esm): Add better ESM support to prerendering

- .github/workflows/ci.yml
Get rid of all the individual `-skip` jobs, and instead have a single job at the end that checks all required jobs. Then we can have a branch protection rule on just that one job instead
> chore(ci): Use a single ci-status-check job in ci.yml for branch protection

- docs/docs/directives.md
Keeping the CJS way of doing things as the default for now, with just a note on how to update to the ESM way. Once ESM becomes the default I should switch it to be the other way around
> feat(docs): Add note about gql import in ESM apps

- packages/prerender/src/graphql/graphql.ts
- packages/prerender/src/runPrerender.tsx
Pass the import function as an argument to the functions in `graphql.ts` so that they work with both `require()` (for CJS) and `import`-based solutions (for ESM)
> chore(prerender): Make graphql.ts import/require agnostic

- packages/cli/src/commands/setup/mailer/mailerHandler.js
Fixes https://github.com/cedarjs/cedar/issues/442
The main issue was a typo in the import attribute `with: { type: 'json ' }` (notice the space after `json`, before the closing quote)
> fix(cli): Mailer setup json import fix

- packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.fetch.test.js
- packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.test.js
Preventing error logs like these
```
Promise returned by `expect(actual).rejects.toThrow(expected)` was not awaited. Vitest currently auto-awaits hanging assertions at the end of the test, but this will cause the test to fail in Vitest 3. Please remember to await the assertion.
at /Users/tobbe/dev/cedarjs/cedar/packages/auth-providers/dbAuth/api/src/__tests__/DbAuthHandler.fetch.test.js:2693:36
```
> chore(dbAuth): Await vitest expect promise

- packages/cli/src/commands/lint.js
Adds support for `--format`, allowing you to pass a formatter for eslint to use
Fixes https://github.com/cedarjs/cedar/issues/451
> feat(cli): Add format option to lint command

- docs/docs/tutorial/intermission.md
- docs/versioned_docs/version-0.12/tutorial/intermission.md
I cloned the (now private) redwood-tutorial repo and put it up here under the CedarJS org.
The tutorial now links to the Cedar version of the repo instead
> docs(tutorial): Update Intermission to point to Cedar tutorial repo

- tasks/git-clean-build.mjs
`git clean -fdx` nukes node_modules inside docs/. This PR adds a `yarn install` inside docs/ to recreate the node_modules folder
> chore(tasks): Run install in docs after git clean

- tasks/framework-tools/tarsync/debug-task-scheduling.mts
Typecasting to get rid of TS error. It's just for the error reporting, so this is good enough for now. If I need better errors I'll come back to this later
> chore(nx): Fix TS error in debug tooling
