package.json, yarn.lock
* Add support for boolean value for color option (https://github.com/sindresorhus/ora/pull/244) https://github.com/sindresorhus/ora/commit/fe951e57c71fefde94f4d7205ce360e5568af06b
=> chore(deps): Bump ora to 8.2.0

README.md
Update readme to talk about Redmix
=> chore(docs): Update README for Redmix

README.md
=> chore(docs): Update sponsor logos

packages/cli/package.json, packages/cli/src/commands/deploy/__tests__/baremetal.test.js, packages/cli/src/commands/deploy/baremetal.js, packages/cli/src/commands/deploy/baremetal/SshExecutor.js, yarn.lock
Also adding a very basic test to test to the `yarn rw deploy barmetal` handler function
=> chore(cli): Remove `require` from Baremetal SshExecutor

packages/cli/src/commands/destroy/component/__tests__/component.test.js, packages/cli/src/commands/destroy/component/component.js, packages/cli/src/commands/generate/component/__tests__/component.test.ts, packages/cli/src/commands/generate/component/component.js, packages/cli/src/commands/generate/component/componentHandler.js
Same as https://github.com/redmix-run/redmix/pull/30 but for `yarn rw g component`
=> chore(cli): async componentHandler() (ESM prep)

packages/cli/src/commands/destroy/directive/__tests__/directive.test.js, packages/cli/src/commands/destroy/directive/directive.js, packages/cli/src/commands/generate/component/__tests__/component.test.ts, packages/cli/src/commands/generate/directive/__tests__/directive.test.ts, packages/cli/src/commands/generate/directive/directive.js, packages/cli/src/commands/generate/directive/directiveHandler.js
Same as https://github.com/redmix-run/redmix/pull/30 but for `yarn rw g directive`
=> perf(cli): async directiveHandler() (ESM prep)

packages/cli/src/commands/execHandler.js, packages/cli/src/lib/generatePrismaClient.js, packages/cli/src/lib/index.js
Continuation of https://github.com/redmix-run/redmix/pull/55
=> fix(exec): Better --silent support

README.md
Add TwoDots as a sponsor in the README
=> chore(README): Add TwoDots as a sponsor

README.md
* Change logo
* Tweak top text in Readme
=> chore(docs): Tweak Readme for CedarJS

packages/create-cedar-app/src/create-cedar-app.js, packages/create-cedar-app/tests/e2e.test.ts
Change to a design that's not dependent on character width alignment
=> feat(ccra): Update welcome design

packages/create-cedar-app/src/create-cedar-app.js, packages/create-cedar-app/tests/e2e.test.ts, packages/create-cedar-app/tests/e2e_prompts.sh, packages/create-cedar-app/tests/e2e_prompts_git.sh, packages/create-cedar-app/tests/e2e_prompts_m.sh, packages/create-cedar-app/tests/e2e_prompts_overwrite.sh, packages/create-cedar-app/tests/e2e_prompts_ts.sh
=> fix(ccra): More CedarJS, less Redwood

__fixtures__/test-project/web/package.json
Need this for other PRs to pass CI
=> chore(test-project): Bump postcss to 8.5.4

docs/README.md, docs/netlify.toml
Running out of memory trying to build on Netlify
=> docs(deploy): Try to deploy the docs to Netlify

docs/docusaurus.config.ts, docs/netlify.toml, docs/yarn.lock
Continuation of #110 
Also: More CedarJS branding
=> docs(deploy): Increase node memory for Netlify

docs/package.json, docs/yarn.lock
https://github.com/facebook/docusaurus/releases/tag/v3.8.1
=> chore(deps): Update Docusaurus to v3.8.1

packages/adapters/fastify/web/src/__fixtures__/fallback/web/dist/about.html, packages/adapters/fastify/web/src/__fixtures__/fallback/web/dist/index.html, packages/adapters/fastify/web/src/__fixtures__/main/web/dist/404.html, packages/adapters/fastify/web/src/__fixtures__/main/web/dist/about.html, packages/adapters/fastify/web/src/__fixtures__/main/web/dist/contacts/new.html, packages/adapters/fastify/web/src/__fixtures__/main/web/dist/index.html, packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/404.html, packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/about.html, packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/contacts/new.html, packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/index.html, tasks/server-tests/fixtures/redwood-app/web/dist/404.html, tasks/server-tests/fixtures/redwood-app/web/dist/about.html, tasks/server-tests/fixtures/redwood-app/web/dist/contacts/new.html, tasks/server-tests/fixtures/redwood-app/web/dist/index.html, tasks/smoke-tests/prerender/tests/prerender.spec.ts
Updates smoke tests to expect "Cedar App" instead of "Redwood App"
=> chore(smoke-test): Update default app title

__fixtures__/test-project/web/package.json
Bumping postcss from 8.5.5 to 8.5.6
=> chore(test-project): Update to postcss 8.5.6

packages/vite/package.json, yarn.lock
Bump `@swc/core` from 1.7.28 to 1.12.1
=> chore(deps): Update `@swc/core` to 1.12.1

packages/storybook/package.json, packages/storybook/src/plugins/auto-imports.ts, yarn.lock
See full list of changes here https://github.com/unplugin/unplugin-auto-import/compare/v0.18.3...v19.3.0
=> chore(deps): Update unplugin-auto-import to 19.3.0

__fixtures__/fragment-test-project/web/src/layouts/BlogLayout/BlogLayout.tsx, __fixtures__/test-project/web/src/layouts/BlogLayout/BlogLayout.tsx, docs/docs/how-to/pagination.md, packages/adapters/fastify/web/src/__fixtures__/fallback/web/dist/about.html, packages/adapters/fastify/web/src/__fixtures__/fallback/web/dist/index.html, packages/adapters/fastify/web/src/__fixtures__/main/web/dist/about.html, packages/adapters/fastify/web/src/__fixtures__/main/web/dist/index.html, packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/about.html, packages/api-server/src/__tests__/fixtures/redwood-app/web/dist/index.html, tasks/e2e/cypress/e2e/01-tutorial/codemods/Step2_1_PagesHome.js, tasks/e2e/cypress/e2e/01-tutorial/codemods/Step2_2_PagesAbout.js, tasks/e2e/cypress/e2e/01-tutorial/codemods/Step3_1_LayoutsBlog.js, tasks/e2e/cypress/e2e/01-tutorial/codemods/Step7_1_BlogLayout.js, tasks/e2e/cypress/e2e/01-tutorial/sharedTests.js, tasks/e2e/cypress/e2e/02-cli/02-cli-commands.cy.xs, tasks/server-tests/fixtures/redwood-app/web/dist/about.html, tasks/server-tests/fixtures/redwood-app/web/dist/index.html, tasks/smoke-tests/prerender/tests/prerender.spec.ts, tasks/smoke-tests/serve/tests/contactUs.spec.ts, tasks/smoke-tests/shared/common.ts, tasks/smoke-tests/shared/homePage.ts, tasks/test-project/codemods/blogLayout.js
=> chore(rename): Replace references to "Redwood Blog" with "Cedar Blog"

packages/jobs/src/types.ts
=> fix(cli): jobs: Fix cron jsdocs

package.json, packages/create-cedar-rsc-app/package.json, packages/create-cedar-rsc-app/yarn.lock, packages/framework-tools/package.json, tasks/e2e-background-jobs/run.mts, yarn.lock
See https://github.com/google/zx/releases/tag/8.7.0 for what's new
=> chore(deps): Bump zx to 8.7.0

package.json, packages/create-cedar-rsc-app/package.json, packages/create-cedar-rsc-app/yarn.lock, packages/framework-tools/package.json, tasks/e2e-background-jobs/run.mts, yarn.lock
Testing fix for https://github.com/google/zx/issues/1266
=> chore(jobs): Only use zx, not tree-kill

docs/docs/server-file.md
Adding docs for https://github.com/cedarjs/cedar/pull/189
Copied over from https://github.com/redwoodjs/graphql/pull/12063
=> docs(server-file): discoverFunctionsGlob

packages/ogimage-gen/package.json, packages/storybook/package.json, packages/vite/package.json, yarn.lock
Bumping Vite to close dependabot security alerts
=> chore(deps): Bump vite to 5.4.19

package.json, yarn.lock
See https://github.com/lerna/lerna/compare/v8.1.9...v8.2.3 for a list of changes since the last version we had
=> chore(deps): Bump lerna to 8.2.3

packages/storybook/package.json, packages/storybook/src/plugins/__tests__/mock-auth.test.ts, packages/storybook/vitest.config.ts, yarn.lock
I want to be able to tweak the regex without causing any regressions, so I'm adding unit tests to it
=> chore(storybook): Add unit tests for mock-auth vite plugin

packages/create-cedar-rsc-app/eslint.config.js, packages/create-cedar-rsc-app/framework-tools.ts, packages/create-cedar-rsc-app/publish.ts, packages/create-cedar-rsc-app/src/download.ts, packages/create-cedar-rsc-app/src/index.ts, packages/create-cedar-rsc-app/src/installationDir.ts, packages/create-cedar-rsc-app/src/latest.ts, packages/create-cedar-rsc-app/src/messages.ts, packages/create-cedar-rsc-app/src/prerequisites.ts, packages/create-cedar-rsc-app/src/upgradeToLatestCanary.ts, packages/create-cedar-rsc-app/src/zip.ts
Match source code formatting in the create-cedar-rsc-app package with how we format the source code in the rest of the project
=> chore(create-cedar-rsc-app): Update eslint config and format files

packages/api-server/src/apiCLIConfig.ts, packages/api-server/src/apiCLIConfigHandler.ts, packages/api-server/src/bin.ts, packages/api-server/src/bothCLIConfig.ts, packages/api-server/src/bothCLIConfigHandler.ts, packages/api-server/src/createServer.ts, packages/api-server/src/createServerHelpers.ts, packages/api-server/src/fastify.ts, packages/api-server/src/logFormatter/README.md, packages/api-server/src/logFormatter/bin.ts, packages/api-server/src/plugins/api.ts, packages/api-server/src/plugins/graphql.ts, packages/api-server/src/plugins/lambdaLoader.ts, packages/api-server/src/requestHandlers/awsLambdaFastify.ts, packages/api-server/src/types.ts, packages/api-server/src/watch.ts
Add .js to relative imports to prepare this package for dual mode ESM+CJS builds
=> chore(api-server): Add .js to relative imports (ESM prep)

packages/cli/src/commands/__tests__/dev.test.js
Extracting common TOML config for the test cases
=> chore(cli): Refactor dev.test.js – extract common config

packages/prerender/package.json, packages/prerender/src/graphql/__tests__/node-runner.test.ts, packages/prerender/src/graphql/vite-plugin-cedar-import-dir.ts, packages/vite/package.json, packages/vite/src/plugins/vite-plugin-cedarjs-job-path-injector.ts, yarn.lock
Had to switch from SWC to something else because of this: https://github.com/swc-project/swc/issues/1366
Others have come to the same conclusion, see here: https://github.com/d3jawu/ectype/commit/a2da37f8253dc37456da2a054abbe6a5177c5d54
=> chore(vite plugins): Switch to ast-grep

packages/testing/global.d.ts, packages/testing/src/config/jest/api/jest.setup.ts, packages/testing/tsconfig.build.json, packages/testing/tsconfig.json
- More specific `scenario` types
- Easier to read global type definitions
- DRYer build system
=> chore(testing): Improve types and build system

.github/workflows/background-jobs-e2e.yml, .github/workflows/build-lint-test.yml, .github/workflows/ci.yml, .github/workflows/cli-smoke-tests.yml, .github/workflows/fragments-smoke-tests.yml, .github/workflows/rsc-smoke-tests.yml, .github/workflows/server-tests.yml, .github/workflows/ssr-smoke-tests.yml, .github/workflows/telemetry-check.yml, .github/workflows/tutorial-e2e.yml
The main ci.yml file is now much shorter and easier to understand. All the logic for each individual job has been extracted out into separate files, making code overview and navigation much simpler
=> chore(ci): Extract jobs logic out of ci.yml

docs/docs/background-jobs.md
Give a clear example on how to do the initial setup/scheduling of a recurring job
=> docs(jobs): Update cron jobs section

packages/testing/src/api/vitest/vitest-api.setup.ts
Fix this
```
[lint:fw] /Users/tobbe/dev/cedarjs/cedar/packages/testing/src/api/vitest/vitest-api.setup.ts
[lint:fw]   293:9  warning  Unused eslint-disable directive (no problems were reported)
```
=> chore(eslint): Remove unused eslint-disable directive

.github/scripts/publish-release-candidate.ts, .github/workflows/publish-release-candidate.yml
Makes it possible to use RC releases for full/proper e2e tests
=> chore(ci): Publish RC version with RC package references

docs/docusaurus.config.ts
Add option to docusaurus-plugin-llms.txt to generate llms-full.txt
=> feat(docs): llms-full.txt

docs/docusaurus.config.ts, docs/package.json, docs/yarn.lock
=> feat(docs): Add button to copy md of page
